name: GSM-Networking On Main Merge CI

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up JDK 17 job has success
        if: ${{ success() }}
        run: echo "jdk 17 job succeeded"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name : Setup Gradle's permission
        run : chmod +x gradlew

      - name: Run build with Gradle wrapper
        run: ./gradlew clean build

      - name: GSM-Networking-server CI success
        if: ${{ success() }}
        run: echo "GSM-Networking-server CI success"